project:
  type: book

page-navigation: true
lightbox: true

format: 
  html:
    theme: cosmo
    code-fold: true
    code-copy: true
    code-overflow: wrap
    toc: false
    number-depth: 1
    link-external-newwindow: true
    
execute:
  message: false
  warning: false  
  

book:
  reader-mode: false
  title: "Epi Methods 2 Review"
  author: "Val"
  date: "2025"  
  sidebar:
    search: true
    style: docked
    pinned: true

  chapters:
    - index.qmd
    - chapters/02a_Causality.qmd
    - chapters/02b_Exchangability.qmd
    - chapters/02c_DAG_Intro.qmd
    - chapters/03b_Risk_vs_Rate.qmd
    - chapters/03c_Population_Types.qmd
    - chapters/03d_Incidence_Density_Rates.qmd
    - chapters/03e_Cumulative_Incidence.qmd
    - chapters/03f_Relationships_MOAs.qmd

    - part: "Types of Studies"
      chapters: 
        - chapters/05a_Cohort_Studies.qmd
        - chapters/05c_Case_Control_Studies.qmd
        - chapters/05d_CrossSectional_Ecological_Studies.qmd 
    
    - part: "Bias and Confounding"
      chapters: 
        - chapters/06b_Bias.qmd
        - chapters/10a_Confounding.qmd
        - chapters/10b_Negative_Controls.qmd 

    - part: "Effect Measure Modification"
      chapters: 
        - chapters/11a_EMM.qmd
        - chapters/11b_EMM_component_cause_model.qmd
        - chapters/11c_EMM_potential_outcomes.qmd
        - chapters/11d_additive_scale_interaction.qmd

    - part: "Matching"
      chapters: 
        - chapters/12a_Matching.qmd
        - chapters/12b_Overmatching.qmd
        - chapters/12c_Matched_Analysis.qmd
        - chapters/12d_Screening_Measures.qmd
        
    - part: "Regression"
      chapters: 
        - chapters/13a_Linear_Regression.qmd
        - chapters/13b_Log_Linear_Regression.qmd
        - chapters/13c_Logistic_Regression.qmd
        - chapters/13d_Survival_Data_Models.qmd
        - chapters/13e_Matched_Case_Control_Models.qmd             
        
        
    - chapters/14a_Propensity_Scores.qmd
    - chapters/14b_Sample_Size_Power.qmd
    - chapters/14c_IPTW_G_computation.qmd
    - chapters/15a_Meta_Analysis.qmd
    - chapters/15b_Population_Intervention_Effects.qmd
    - chapters/15c_Spillover_Effects.qmd
    - chapters/15d_Replication_Transparency_Reproducibility.qmd
    
    
    - part: "Exam Review"
      chapters: 
        - chapters/01_exam_prep1.qmd
        - chapters/01b_exam_prep2.qmd   
    
    